version: '3'
services:
  mariadb:
    container_name: mariadb
    image: "mariadb"
    environment:
      MARIADB_ROOT_PASSWORD: "Zaq12wsx"
    networks:
      - siec
    volumes:
      - /home/daniel/ASK2/:/var/lib/mysql
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - siec
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka-broker:
    image: confluentinc/cp-kafka:6.1.1
    hostname: broker
    container_name: broker
    networks:
      - siec
    depends_on:
    - zookeeper
    ports:
    - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  python-producer:
    image: python-producer:1
    container_name: python-producer
    networks:
      - siec
    depends_on:
      - kafka-broker
      - mariadb 
  python-consumer:
    image: python-consumer:1
    container_name: python-consumer
    environment:
      DB_HOST: 'mariadb'
      DB_PORT: '3306'
      DB_USER: 'python'
      DB_PASS: 'Zaq12wsx'
    networks:
      - siec    
    depends_on:
      - kafka-broker
      - mariadb 
networks:
  siec:
    ipam:
      config:
        - subnet: 172.38.141.0/24
